name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: avsm/setup-ocaml@v1.0
    - run: opam pin add aoc2019.dev -n .
    - run: opam depext -yt aoc2019
    - run: opam install -t . --deps-only
    - run: opam exec -- dune build
    - run: opam exec -- dune runtest
