open! Core
open! Async
open! Import

module Bag = struct
  type t = { color : string } [@@deriving compare, equal, hash, sexp_of]

  include (val Comparator.make ~compare ~sexp_of_t)
end

module Input = struct
  type t = (Bag.t, (int * Bag.t) list) Hashtbl.t [@@deriving sexp_of]

  let rule_re, contained_re =
    let open Re in
    let color = seq [ rep1 alpha; str " "; rep1 alpha ] in
    let bags = alt [ str "bag"; str "bags" ] in
    let contained = seq [ group (rep1 digit); str " "; group color; str " "; bags ] in
    ( compile
        (seq
           [ group color
           ; str " "
           ; bags
           ; str " contain "
           ; group
               (alt
                  [ str "no other bags"
                  ; seq [ contained; rep (seq [ str ", "; contained ]) ]
                  ])
           ; str "."
           ])
    , compile contained )
  ;;

  let parse input : t =
    input
    |> String.split_lines
    |> List.map ~f:(fun line ->
      let g = Re.exec rule_re line in
      let from_color = Re.Group.get g 1 in
      let contained = Re.Group.get g 2 in
      let to_colors =
        match contained with
        | "no other bags" -> []
        | _ ->
          Re.split Re.(compile (str ", ")) contained
          |> List.map ~f:(fun contained ->
            let g = Re.exec contained_re contained in
            let count = Re.Group.get g 1 |> Int.of_string in
            let color = Re.Group.get g 2 in
            count, ({ color } : Bag.t))
      in
      ({ color = from_color } : Bag.t), to_colors)
    |> Hashtbl.of_alist_exn (module Bag)
  ;;

  let t : t Lazy_deferred.t =
    Lazy_deferred.create (fun () -> Reader.file_contents "input.txt" >>| parse)
  ;;
end

let rec find_bags_containing rules ~bag =
  let next =
    Hashtbl.to_alist rules
    |> List.filter_map ~f:(fun (from, to_) ->
      if List.exists to_ ~f:(fun (_, bag') -> Bag.equal bag bag')
      then Some from
      else None)
  in
  next @ List.concat_map next ~f:(fun bag -> find_bags_containing rules ~bag)
;;

let a () =
  let%bind rules = Lazy_deferred.force_exn Input.t in
  let bags =
    find_bags_containing rules ~bag:{ color = "shiny gold" } |> Set.of_list (module Bag)
  in
  let bags = Set.remove bags { color = "shiny gold" } in
  print_s [%sexp (Set.length bags : int)];
  return ()
;;

let%expect_test "a" =
  let%bind () = a () in
  let%bind () = [%expect {| 144 |}] in
  return ()
;;

let b () =
  let%bind input = Lazy_deferred.force_exn Input.t in
  print_s [%sexp (input : Input.t)];
  return ()
;;

let%expect_test "b" =
  let%bind () = b () in
  let%bind () =
    [%expect
      {|
    ((((color "bright aqua"))
      ((5 ((color "mirrored purple")))
       (1 ((color "dull maroon")))))
     (((color "bright beige"))
      ((2 ((color "pale beige")))
       (2 ((color "dark lavender")))
       (1 ((color "dull teal")))))
     (((color "bright black")) ((3 ((color "mirrored lime")))))
     (((color "bright blue"))
      ((1 ((color "plaid cyan")))
       (4 ((color "dim magenta")))
       (2 ((color "drab magenta")))))
     (((color "bright bronze"))
      ((5 ((color "dotted purple")))
       (4 ((color "shiny brown")))))
     (((color "bright brown"))
      ((2 ((color "plaid salmon")))
       (4 ((color "faded indigo")))))
     (((color "bright chartreuse")) ((2 ((color "bright tomato")))))
     (((color "bright coral"))
      ((3 ((color "drab tan")))
       (4 ((color "pale beige")))
       (4 ((color "clear turquoise")))
       (1 ((color "faded white")))))
     (((color "bright crimson"))
      ((4 ((color "vibrant tan")))
       (2 ((color "dotted gold")))
       (5 ((color "striped purple")))))
     (((color "bright cyan"))
      ((4 ((color "pale turquoise")))
       (4 ((color "dull yellow")))))
     (((color "bright fuchsia"))
      ((2 ((color "light cyan")))
       (3 ((color "vibrant chartreuse")))
       (4 ((color "wavy yellow")))
       (2 ((color "vibrant olive")))))
     (((color "bright gold"))
      ((3 ((color "dim orange")))
       (5 ((color "dark gray")))
       (2 ((color "clear fuchsia")))
       (5 ((color "clear maroon")))))
     (((color "bright gray"))
      ((2 ((color "wavy gray")))
       (4 ((color "clear maroon")))))
     (((color "bright green"))
      ((1 ((color "drab silver")))
       (5 ((color "bright bronze")))))
     (((color "bright indigo"))
      ((1 ((color "muted teal")))
       (4 ((color "faded silver")))
       (3 ((color "dim indigo")))))
     (((color "bright lavender"))
      ((1 ((color "drab lime")))
       (4 ((color "plaid olive")))
       (3 ((color "pale blue")))))
     (((color "bright lime"))
      ((5 ((color "mirrored turquoise")))
       (1 ((color "clear plum")))
       (3 ((color "dull aqua")))
       (1 ((color "drab green")))))
     (((color "bright magenta"))
      ((2 ((color "dim magenta")))
       (3 ((color "dotted gold")))
       (4 ((color "posh gold")))))
     (((color "bright maroon"))
      ((3 ((color "vibrant green")))
       (5 ((color "shiny gold")))))
     (((color "bright olive"))
      ((4 ((color "pale green")))
       (2 ((color "wavy red")))))
     (((color "bright orange"))
      ((3 ((color "muted tomato")))
       (2 ((color "pale black")))))
     (((color "bright plum"))
      ((1 ((color "bright blue")))
       (2 ((color "faded orange")))
       (2 ((color "dim coral")))
       (3 ((color "dotted cyan")))))
     (((color "bright purple"))
      ((1 ((color "striped purple")))
       (3 ((color "shiny brown")))
       (4 ((color "vibrant indigo")))))
     (((color "bright red"))
      ((1 ((color "clear magenta")))
       (4 ((color "striped aqua")))
       (2 ((color "posh cyan")))
       (1 ((color "dull salmon")))))
     (((color "bright salmon"))
      ((1 ((color "muted silver")))
       (1 ((color "drab purple")))
       (5 ((color "pale cyan")))))
     (((color "bright silver"))
      ((3 ((color "pale beige")))
       (4 ((color "bright beige")))
       (3 ((color "wavy maroon")))
       (1 ((color "drab chartreuse")))))
     (((color "bright tan"))
      ((1 ((color "vibrant lavender")))
       (1 ((color "vibrant salmon")))
       (1 ((color "dim green")))))
     (((color "bright teal"))
      ((1 ((color "shiny brown")))
       (4 ((color "vibrant tan")))))
     (((color "bright tomato"))
      ((1 ((color "dotted purple")))
       (2 ((color "dotted chartreuse")))
       (2 ((color "wavy yellow")))))
     (((color "bright turquoise")) ((3 ((color "pale white")))))
     (((color "bright violet"))
      ((4 ((color "posh salmon")))
       (1 ((color "shiny bronze")))
       (1 ((color "vibrant indigo")))))
     (((color "bright white"))
      ((3 ((color "dotted purple")))
       (5 ((color "bright violet")))))
     (((color "bright yellow"))
      ((1 ((color "pale gold")))
       (5 ((color "shiny maroon")))))
     (((color "clear aqua"))
      ((4 ((color "dotted lavender")))
       (1 ((color "striped purple")))
       (3 ((color "light purple")))))
     (((color "clear beige")) ((4 ((color "dark maroon")))))
     (((color "clear black"))
      ((4 ((color "vibrant brown")))
       (5 ((color "pale tomato")))
       (4 ((color "bright teal")))
       (3 ((color "wavy brown")))))
     (((color "clear blue")) ((1 ((color "faded tan")))))
     (((color "clear bronze")) ((1 ((color "dull salmon")))))
     (((color "clear brown"))
      ((3 ((color "posh olive")))
       (1 ((color "drab silver")))
       (5 ((color "dark purple")))))
     (((color "clear chartreuse")) ((3 ((color "light coral")))))
     (((color "clear coral")) ((5 ((color "plaid maroon")))))
     (((color "clear crimson"))
      ((4 ((color "wavy blue")))
       (5 ((color "dim chartreuse")))
       (1 ((color "plaid maroon")))
       (4 ((color "dull cyan")))))
     (((color "clear cyan"))
      ((4 ((color "mirrored plum")))
       (3 ((color "dotted purple")))
       (1 ((color "dull fuchsia")))
       (5 ((color "bright teal")))))
     (((color "clear fuchsia"))
      ((4 ((color "plaid brown")))
       (4 ((color "dim bronze")))
       (1 ((color "posh lime")))))
     (((color "clear gold"))
      ((5 ((color "dark aqua")))
       (1 ((color "shiny coral")))
       (2 ((color "dim fuchsia")))
       (1 ((color "mirrored blue")))))
     (((color "clear gray"))
      ((2 ((color "muted fuchsia")))
       (4 ((color "clear yellow")))))
     (((color "clear green"))
      ((1 ((color "dull magenta")))
       (5 ((color "wavy blue")))
       (1 ((color "vibrant olive")))
       (1 ((color "vibrant tan")))))
     (((color "clear indigo"))
      ((1 ((color "clear beige")))
       (2 ((color "bright silver")))
       (1 ((color "dim salmon")))))
     (((color "clear lavender")) ((1 ((color "dim bronze")))))
     (((color "clear lime")) ((2 ((color "dotted salmon")))))
     (((color "clear magenta"))
      ((1 ((color "clear cyan")))
       (3 ((color "light bronze")))))
     (((color "clear maroon"))
      ((2 ((color "light purple")))
       (2 ((color "dim crimson")))
       (5 ((color "vibrant bronze")))))
     (((color "clear olive")) ((3 ((color "mirrored magenta")))))
     (((color "clear orange"))
      ((4 ((color "mirrored brown")))
       (1 ((color "posh turquoise")))))
     (((color "clear plum")) ())
     (((color "clear purple"))
      ((5 ((color "faded indigo")))
       (3 ((color "striped maroon")))
       (4 ((color "vibrant plum")))
       (3 ((color "light red")))))
     (((color "clear red"))
      ((4 ((color "faded lime")))
       (3 ((color "striped blue")))
       (3 ((color "light fuchsia")))
       (4 ((color "drab turquoise")))))
     (((color "clear salmon"))
      ((1 ((color "striped turquoise")))
       (1 ((color "muted silver")))))
     (((color "clear silver"))
      ((2 ((color "plaid purple")))
       (2 ((color "plaid indigo")))
       (1 ((color "muted orange")))
       (3 ((color "clear plum")))))
     (((color "clear tan"))
      ((4 ((color "dark plum")))
       (1 ((color "posh olive")))))
     (((color "clear teal"))
      ((3 ((color "dark crimson")))
       (1 ((color "bright tomato")))))
     (((color "clear tomato"))
      ((3 ((color "shiny turquoise")))
       (1 ((color "wavy cyan")))
       (1 ((color "bright bronze")))
       (5 ((color "light red")))))
     (((color "clear turquoise"))
      ((5 ((color "light crimson")))
       (4 ((color "dotted cyan")))))
     (((color "clear violet"))
      ((3 ((color "pale cyan")))
       (3 ((color "dull aqua")))
       (4 ((color "pale brown")))
       (5 ((color "dim plum")))))
     (((color "clear white")) ((5 ((color "light turquoise")))))
     (((color "clear yellow"))
      ((4 ((color "striped purple")))
       (5 ((color "mirrored black")))
       (4 ((color "posh gray")))))
     (((color "dark aqua"))
      ((2 ((color "dark indigo")))
       (5 ((color "bright bronze")))))
     (((color "dark beige"))
      ((5 ((color "mirrored black")))
       (3 ((color "dim purple")))
       (5 ((color "light purple")))
       (5 ((color "dark brown")))))
     (((color "dark black"))
      ((5 ((color "dull salmon")))
       (3 ((color "pale silver")))
       (2 ((color "vibrant turquoise")))))
     (((color "dark blue"))
      ((3 ((color "clear teal")))
       (1 ((color "dim bronze")))
       (4 ((color "light tan")))
       (4 ((color "wavy indigo")))))
     (((color "dark bronze"))
      ((2 ((color "dim teal")))
       (4 ((color "dark maroon")))))
     (((color "dark brown")) ((1 ((color "plaid indigo")))))
     (((color "dark chartreuse")) ((5 ((color "plaid silver")))))
     (((color "dark coral"))
      ((4 ((color "pale blue")))
       (3 ((color "wavy yellow")))
       (4 ((color "vibrant tan")))
       (3 ((color "striped purple")))))
     (((color "dark crimson")) ((1 ((color "shiny brown")))))
     (((color "dark cyan")) ((3 ((color "clear tomato")))))
     (((color "dark fuchsia"))
      ((4 ((color "bright teal")))
       (4 ((color "dim blue")))
       (5 ((color "vibrant lavender")))
       (4 ((color "striped yellow")))))
     (((color "dark gold"))
      ((4 ((color "muted fuchsia")))
       (4 ((color "light salmon")))))
     (((color "dark gray"))
      ((3 ((color "plaid gray")))
       (2 ((color "clear yellow")))
       (5 ((color "posh gray")))))
     (((color "dark green")) ((5 ((color "clear tan")))))
     (((color "dark indigo"))
      ((3 ((color "pale gray")))
       (4 ((color "mirrored orange")))
       (1 ((color "vibrant gray")))))
     (((color "dark lavender"))
      ((1 ((color "shiny salmon")))
       (4 ((color "wavy cyan")))
       (5 ((color "dim lavender")))))
     (((color "dark lime"))
      ((2 ((color "plaid white")))
       (2 ((color "bright gray")))))
     (((color "dark magenta"))
      ((1 ((color "drab violet")))
       (2 ((color "bright purple")))
       (4 ((color "shiny coral")))
       (5 ((color "striped tan")))))
     (((color "dark maroon"))
      ((2 ((color "striped silver")))
       (4 ((color "mirrored maroon")))
       (5 ((color "shiny gold")))
       (1 ((color "dotted gold")))))
     (((color "dark olive"))
      ((4 ((color "striped gold")))
       (1 ((color "striped gray")))
       (1 ((color "bright tomato")))))
     (((color "dark orange"))
      ((5 ((color "dark maroon")))
       (2 ((color "drab cyan")))
       (1 ((color "dotted chartreuse")))
       (5 ((color "shiny green")))))
     (((color "dark plum"))
      ((2 ((color "pale white")))
       (5 ((color "dim plum")))))
     (((color "dark purple"))
      ((4 ((color "dotted purple")))
       (3 ((color "striped yellow")))
       (5 ((color "vibrant purple")))
       (3 ((color "mirrored lavender")))))
     (((color "dark red"))
      ((3 ((color "wavy red")))
       (4 ((color "dotted violet")))
       (5 ((color "pale tomato")))))
     (((color "dark salmon")) ((1 ((color "pale crimson")))))
     (((color "dark silver"))
      ((1 ((color "shiny tan")))
       (3 ((color "wavy yellow")))
       (4 ((color "drab violet")))))
     (((color "dark tan"))
      ((5 ((color "striped lime")))
       (1 ((color "dark purple")))
       (5 ((color "faded gold")))))
     (((color "dark teal"))
      ((3 ((color "dull yellow")))
       (3 ((color "plaid white")))
       (3 ((color "clear cyan")))
       (4 ((color "striped red")))))
     (((color "dark tomato"))
      ((3 ((color "pale yellow")))
       (2 ((color "bright red")))))
     (((color "dark turquoise"))
      ((4 ((color "dotted silver")))
       (3 ((color "vibrant chartreuse")))
       (4 ((color "striped green")))
       (2 ((color "dotted black")))))
     (((color "dark violet")) ((4 ((color "dark purple")))))
     (((color "dark white"))
      ((1 ((color "drab green")))
       (4 ((color "dotted chartreuse")))))
     (((color "dark yellow"))
      ((2 ((color "pale gray")))
       (1 ((color "shiny blue")))
       (4 ((color "faded turquoise")))))
     (((color "dim aqua")) ((4 ((color "faded coral")))))
     (((color "dim beige"))
      ((4 ((color "dull green")))
       (2 ((color "dim green")))))
     (((color "dim black"))
      ((2 ((color "vibrant cyan")))
       (3 ((color "shiny turquoise")))
       (2 ((color "dotted turquoise")))
       (1 ((color "muted orange")))))
     (((color "dim blue")) ((3 ((color "posh silver")))))
     (((color "dim bronze"))
      ((1 ((color "drab magenta")))
       (1 ((color "mirrored gray")))
       (2 ((color "striped purple")))))
     (((color "dim brown"))
      ((1 ((color "drab bronze")))
       (5 ((color "shiny yellow")))
       (1 ((color "pale olive")))
       (2 ((color "drab silver")))))
     (((color "dim chartreuse"))
      ((1 ((color "drab bronze")))
       (2 ((color "mirrored maroon")))
       (3 ((color "dark salmon")))
       (5 ((color "light coral")))))
     (((color "dim coral"))
      ((3 ((color "vibrant indigo")))
       (4 ((color "vibrant turquoise")))))
     (((color "dim crimson"))
      ((1 ((color "vibrant indigo")))
       (4 ((color "pale crimson")))))
     (((color "dim cyan"))
      ((4 ((color "shiny salmon")))
       (3 ((color "striped white")))
       (3 ((color "plaid chartreuse")))))
     (((color "dim fuchsia"))
      ((3 ((color "shiny blue")))
       (1 ((color "dark bronze")))
       (2 ((color "wavy yellow")))))
     (((color "dim gold")) ((2 ((color "wavy magenta")))))
     (((color "dim gray"))
      ((2 ((color "bright salmon")))
       (2 ((color "clear silver")))
       (2 ((color "light turquoise")))
       (4 ((color "drab plum")))))
     (((color "dim green"))
      ((3 ((color "vibrant turquoise")))
       (5 ((color "faded tan")))))
     (((color "dim indigo"))
      ((5 ((color "plaid gray")))
       (4 ((color "pale maroon")))
       (2 ((color "bright maroon")))
       (3 ((color "dark fuchsia")))))
     (((color "dim lavender"))
      ((3 ((color "dark indigo")))
       (3 ((color "wavy orange")))
       (5 ((color "faded orange")))
       (2 ((color "striped orange")))))
     (((color "dim lime"))
      ((5 ((color "dull indigo")))
       (1 ((color "wavy olive")))))
     (((color "dim magenta"))
      ((2 ((color "plaid coral")))
       (2 ((color "faded orange")))))
     (((color "dim maroon"))
      ((1 ((color "wavy crimson")))
       (2 ((color "faded tan")))))
     (((color "dim olive"))
      ((3 ((color "pale white")))
       (1 ((color "posh olive")))
       (3 ((color "striped orange")))
       (1 ((color "striped silver")))))
     (((color "dim orange")) ((3 ((color "faded blue")))))
     (((color "dim plum"))
      ((2 ((color "vibrant indigo")))
       (4 ((color "faded orange")))
       (3 ((color "wavy cyan")))))
     (((color "dim purple"))
      ((2 ((color "striped silver")))
       (1 ((color "plaid blue")))
       (5 ((color "pale cyan")))))
     (((color "dim red"))
      ((1 ((color "vibrant green")))
       (2 ((color "drab tan")))
       (1 ((color "mirrored brown")))))
     (((color "dim salmon")) ((3 ((color "dotted silver")))))
     (((color "dim silver"))
      ((5 ((color "mirrored silver")))
       (1 ((color "vibrant turquoise")))
       (5 ((color "wavy turquoise")))))
     (((color "dim tan"))
      ((2 ((color "dim chartreuse")))
       (3 ((color "vibrant turquoise")))
       (2 ((color "faded coral")))
       (2 ((color "dim coral")))))
     (((color "dim teal"))
      ((5 ((color "dark brown")))
       (5 ((color "dark crimson")))
       (5 ((color "dull aqua")))))
     (((color "dim tomato"))
      ((4 ((color "clear gold")))
       (4 ((color "bright crimson")))
       (4 ((color "light beige")))
       (4 ((color "striped white")))))
     (((color "dim turquoise"))
      ((2 ((color "pale brown")))
       (4 ((color "bright green")))
       (1 ((color "drab salmon")))))
     (((color "dim violet")) ((1 ((color "dotted chartreuse")))))
     (((color "dim white")) ((5 ((color "mirrored white")))))
     (((color "dim yellow"))
      ((1 ((color "dull orange")))
       (1 ((color "muted purple")))
       (2 ((color "faded indigo")))
       (5 ((color "dotted plum")))))
     (((color "dotted aqua"))
      ((2 ((color "wavy green")))
       (5 ((color "vibrant tomato")))))
     (((color "dotted beige"))
      ((5 ((color "posh black")))
       (2 ((color "mirrored yellow")))
       (3 ((color "mirrored salmon")))))
     (((color "dotted black"))
      ((4 ((color "wavy lime")))
       (1 ((color "faded salmon")))
       (3 ((color "pale blue")))
       (5 ((color "wavy blue")))))
     (((color "dotted blue"))
      ((3 ((color "dotted tan")))
       (4 ((color "muted violet")))))
     (((color "dotted bronze"))
      ((2 ((color "striped yellow")))
       (3 ((color "dark maroon")))))
     (((color "dotted brown"))
      ((2 ((color "faded blue")))
       (5 ((color "shiny lavender")))
       (4 ((color "clear lavender")))
       (1 ((color "bright bronze")))))
     (((color "dotted chartreuse"))
      ((5 ((color "dim coral")))
       (1 ((color "dull gray")))
       (2 ((color "posh tomato")))))
     (((color "dotted coral"))
      ((4 ((color "dull indigo")))
       (5 ((color "muted silver")))
       (1 ((color "faded white")))))
     (((color "dotted crimson")) ((2 ((color "dark maroon")))))
     (((color "dotted cyan"))
      ((4 ((color "clear aqua")))
       (5 ((color "plaid gray")))
       (3 ((color "bright bronze")))))
     (((color "dotted fuchsia"))
      ((2 ((color "plaid coral")))
       (5 ((color "dull brown")))
       (1 ((color "dark maroon")))))
     (((color "dotted gold"))
      ((4 ((color "vibrant indigo")))
       (2 ((color "bright bronze")))
       (2 ((color "drab silver")))
       (5 ((color "muted brown")))))
     (((color "dotted gray"))
      ((3 ((color "drab salmon")))
       (1 ((color "dim coral")))))
     (((color "dotted green")) ((5 ((color "posh gray")))))
     (((color "dotted indigo"))
      ((3 ((color "light violet")))
       (4 ((color "dull fuchsia")))))
     (((color "dotted lavender"))
      ((2 ((color "vibrant indigo")))
       (1 ((color "clear plum")))))
     (((color "dotted lime"))
      ((5 ((color "dotted magenta")))
       (5 ((color "dark maroon")))))
     (((color "dotted magenta"))
      ((3 ((color "faded silver")))
       (3 ((color "dull purple")))
       (5 ((color "dotted tan")))))
     (((color "dotted maroon"))
      ((1 ((color "dark orange")))
       (1 ((color "wavy brown")))))
     (((color "dotted olive"))
      ((2 ((color "faded blue")))
       (2 ((color "dull maroon")))
       (3 ((color "dim fuchsia")))
       (5 ((color "light fuchsia")))))
     (((color "dotted orange"))
      ((5 ((color "clear crimson")))
       (2 ((color "bright gold")))
       (2 ((color "dim violet")))
       (3 ((color "faded gray")))))
     (((color "dotted plum"))
      ((4 ((color "posh salmon")))
       (3 ((color "vibrant chartreuse")))
       (5 ((color "dim green")))))
     (((color "dotted purple")) ())
     (((color "dotted red"))
      ((5 ((color "bright purple")))
       (1 ((color "dotted gold")))
       (5 ((color "mirrored magenta")))
       (2 ((color "plaid indigo")))))
     (((color "dotted salmon")) ((2 ((color "clear lavender")))))
     (((color "dotted silver")) ((2 ((color "pale blue")))))
     (((color "dotted tan"))
      ((1 ((color "faded aqua")))
       (3 ((color "pale brown")))
       (5 ((color "dim chartreuse")))))
     (((color "dotted teal"))
      ((4 ((color "pale olive")))
       (5 ((color "mirrored crimson")))))
     (((color "dotted tomato"))
      ((1 ((color "dark coral")))
       (5 ((color "pale plum")))))
     (((color "dotted turquoise"))
      ((3 ((color "dim olive")))
       (3 ((color "light red")))
       (3 ((color "dull fuchsia")))))
     (((color "dotted violet"))
      ((5 ((color "plaid chartreuse")))
       (5 ((color "shiny beige")))
       (2 ((color "clear tan")))))
     (((color "dotted white"))
      ((2 ((color "bright plum")))
       (3 ((color "pale lavender")))
       (2 ((color "muted red")))))
     (((color "dotted yellow")) ((4 ((color "dull gray")))))
     (((color "drab aqua")) ((3 ((color "wavy turquoise")))))
     (((color "drab beige"))
      ((2 ((color "plaid purple")))
       (5 ((color "clear magenta")))
       (3 ((color "faded coral")))
       (2 ((color "clear beige")))))
     (((color "drab black"))
      ((3 ((color "mirrored bronze")))
       (1 ((color "dotted bronze")))
       (5 ((color "light gray")))))
     (((color "drab blue"))
      ((3 ((color "pale tomato")))
       (1 ((color "shiny plum")))))
     (((color "drab bronze")) ((1 ((color "mirrored brown")))))
     (((color "drab brown")) ((3 ((color "striped teal")))))
     (((color "drab chartreuse"))
      ((1 ((color "wavy yellow")))
       (4 ((color "mirrored beige")))
       (4 ((color "dull gold")))
       (5 ((color "dull plum")))))
     (((color "drab coral"))
      ((5 ((color "mirrored brown")))
       (5 ((color "dotted lavender")))
       (1 ((color "drab bronze")))
       (3 ((color "dim chartreuse")))))
     (((color "drab crimson"))
      ((2 ((color "clear salmon")))
       (2 ((color "clear orange")))
       (1 ((color "striped yellow")))))
     (((color "drab cyan"))
      ((2 ((color "wavy green")))
       (2 ((color "pale gray")))
       (2 ((color "dotted purple")))
       (3 ((color "dark beige")))))
     (((color "drab fuchsia"))
      ((1 ((color "dim plum")))
       (1 ((color "striped red")))
       (2 ((color "vibrant cyan")))))
     (((color "drab gold")) ((5 ((color "mirrored beige")))))
     (((color "drab gray"))
      ((3 ((color "striped crimson")))
       (2 ((color "shiny gold")))
       (2 ((color "shiny magenta")))))
     (((color "drab green"))
      ((4 ((color "mirrored maroon")))
       (2 ((color "vibrant aqua")))
       (4 ((color "dim olive")))))
     (((color "drab indigo"))
      ((3 ((color "shiny aqua")))
       (4 ((color "dotted lavender")))
       (4 ((color "dim brown")))
       (2 ((color "faded purple")))))
     (((color "drab lavender")) ((1 ((color "shiny green")))))
     (((color "drab lime")) ((3 ((color "dim magenta")))))
     (((color "drab magenta")) ((1 ((color "plaid coral")))))
     (((color "drab maroon"))
      ((1 ((color "faded salmon")))
       (1 ((color "dotted orange")))
       (1 ((color "faded fuchsia")))))
     (((color "drab olive"))
      ((5 ((color "vibrant green")))
       (4 ((color "dull turquoise")))
       (4 ((color "muted fuchsia")))))
     (((color "drab orange"))
      ((5 ((color "vibrant brown")))
       (5 ((color "striped bronze")))))
     (((color "drab plum"))
      ((2 ((color "clear turquoise")))
       (5 ((color "striped violet")))
       (5 ((color "muted black")))))
     (((color "drab purple"))
      ((1 ((color "shiny green")))
       (5 ((color "wavy gray")))))
     (((color "drab red"))
      ((2 ((color "muted tomato")))
       (3 ((color "dim bronze")))
       (2 ((color "mirrored black")))
       (4 ((color "faded salmon")))))
     (((color "drab salmon"))
      ((3 ((color "dark coral")))
       (2 ((color "wavy brown")))
       (1 ((color "striped purple")))
       (4 ((color "dull gray")))))
     (((color "drab silver"))
      ((1 ((color "vibrant aqua")))
       (5 ((color "vibrant tan")))))
     (((color "drab tan"))
      ((2 ((color "dull indigo")))
       (3 ((color "faded tan")))))
     (((color "drab teal"))
      ((4 ((color "clear crimson")))
       (5 ((color "wavy lime")))
       (4 ((color "plaid turquoise")))))
     (((color "drab tomato")) ((3 ((color "pale brown")))))
     (((color "drab turquoise"))
      ((3 ((color "light gold")))
       (1 ((color "striped blue")))
       (2 ((color "dark maroon")))))
     (((color "drab violet"))
      ((3 ((color "bright turquoise")))
       (1 ((color "posh olive")))
       (2 ((color "wavy olive")))))
     (((color "drab white")) ((5 ((color "muted yellow")))))
     (((color "drab yellow"))
      ((5 ((color "dull teal")))
       (2 ((color "plaid turquoise")))))
     (((color "dull aqua")) ((2 ((color "wavy yellow")))))
     (((color "dull beige"))
      ((3 ((color "dull lime")))
       (2 ((color "wavy coral")))
       (1 ((color "plaid yellow")))))
     (((color "dull black")) ((4 ((color "drab bronze")))))
     (((color "dull blue")) ((5 ((color "dark maroon")))))
     (((color "dull bronze")) ((5 ((color "bright coral")))))
     (((color "dull brown"))
      ((5 ((color "dotted purple")))
       (5 ((color "vibrant turquoise")))))
     (((color "dull chartreuse"))
      ((2 ((color "dull bronze")))
       (3 ((color "light gold")))
       (2 ((color "striped white")))))
     (((color "dull coral"))
      ((4 ((color "faded salmon")))
       (2 ((color "pale aqua")))
       (5 ((color "dull aqua")))
       (4 ((color "dull silver")))))
     (((color "dull crimson")) ((5 ((color "shiny tomato")))))
     (((color "dull cyan"))
      ((2 ((color "clear teal")))
       (4 ((color "plaid blue")))))
     (((color "dull fuchsia"))
      ((2 ((color "dark coral")))
       (3 ((color "light coral")))))
     (((color "dull gold")) ((5 ((color "dotted lavender")))))
     (((color "dull gray"))
      ((4 ((color "vibrant indigo")))
       (2 ((color "pale crimson")))
       (2 ((color "clear plum")))))
     (((color "dull green"))
      ((1 ((color "striped tan")))
       (1 ((color "dull magenta")))))
     (((color "dull indigo")) ((4 ((color "striped purple")))))
     (((color "dull lavender"))
      ((5 ((color "posh tomato")))
       (4 ((color "faded tan")))))
     (((color "dull lime")) ((4 ((color "dim salmon")))))
     (((color "dull magenta"))
      ((4 ((color "pale blue")))
       (2 ((color "shiny bronze")))
       (2 ((color "pale lavender")))
       (3 ((color "pale chartreuse")))))
     (((color "dull maroon"))
      ((2 ((color "bright orange")))
       (5 ((color "vibrant bronze")))
       (4 ((color "drab chartreuse")))))
     (((color "dull olive"))
      ((1 ((color "dim maroon")))
       (4 ((color "striped gold")))
       (2 ((color "shiny white")))
       (3 ((color "clear tomato")))))
     (((color "dull orange"))
      ((2 ((color "pale salmon")))
       (2 ((color "posh olive")))
       (2 ((color "dark coral")))
       (1 ((color "plaid coral")))))
     (((color "dull plum"))
      ((3 ((color "striped silver")))
       (4 ((color "clear violet")))))
     (((color "dull purple"))
      ((2 ((color "vibrant aqua")))
       (2 ((color "bright blue")))))
     (((color "dull red"))
      ((1 ((color "striped teal")))
       (2 ((color "dark violet")))
       (1 ((color "shiny tomato")))
       (1 ((color "striped yellow")))))
     (((color "dull salmon"))
      ((3 ((color "dark indigo")))
       (2 ((color "striped gray")))))
     (((color "dull silver"))
      ((3 ((color "clear turquoise")))
       (3 ((color "dim salmon")))))
     (((color "dull tan"))
      ((3 ((color "light black")))
       (4 ((color "faded brown")))
       (2 ((color "pale bronze")))
       (3 ((color "shiny lavender")))))
     (((color "dull teal"))
      ((3 ((color "mirrored black")))
       (4 ((color "dark plum")))
       (2 ((color "drab silver")))
       (4 ((color "mirrored gray")))))
     (((color "dull tomato"))
      ((2 ((color "dim beige")))
       (1 ((color "dotted brown")))
       (3 ((color "faded magenta")))
       (4 ((color "faded gray")))))
     (((color "dull turquoise"))
      ((3 ((color "faded coral")))
       (2 ((color "bright green")))))
     (((color "dull violet"))
      ((2 ((color "dotted tan")))
       (4 ((color "pale cyan")))))
     (((color "dull white"))
      ((4 ((color "dim chartreuse")))
       (5 ((color "vibrant coral")))
       (2 ((color "muted indigo")))))
     (((color "dull yellow")) ((3 ((color "clear cyan")))))
     (((color "faded aqua"))
      ((4 ((color "shiny gold")))
       (5 ((color "pale tomato")))
       (1 ((color "plaid blue")))
       (1 ((color "faded coral")))))
     (((color "faded beige")) ((2 ((color "muted red")))))
     (((color "faded black"))
      ((2 ((color "clear crimson")))
       (4 ((color "posh gray")))))
     (((color "faded blue")) ((5 ((color "dull magenta")))))
     (((color "faded bronze")) ((3 ((color "dull orange")))))
     (((color "faded brown")) ((3 ((color "wavy turquoise")))))
     (((color "faded chartreuse")) ((4 ((color "vibrant yellow")))))
     (((color "faded coral"))
      ((3 ((color "dull aqua")))
       (3 ((color "wavy orange")))
       (3 ((color "drab chartreuse")))
       (4 ((color "muted olive")))))
     (((color "faded crimson")) ((3 ((color "clear coral")))))
     (((color "faded cyan"))
      ((4 ((color "clear orange")))
       (5 ((color "dull orange")))
       (4 ((color "dotted bronze")))))
     (((color "faded fuchsia"))
      ((4 ((color "faded tan")))
       (1 ((color "clear silver")))
       (1 ((color "faded tomato")))))
     (((color "faded gold"))
      ((2 ((color "posh salmon")))
       (4 ((color "plaid white")))
       (2 ((color "dull cyan")))))
     (((color "faded gray"))
      ((2 ((color "drab lime")))
       (4 ((color "clear maroon")))
       (1 ((color "mirrored silver")))
       (1 ((color "shiny brown")))))
     (((color "faded green"))
      ((3 ((color "dotted turquoise")))
       (2 ((color "dull bronze")))
       (2 ((color "muted green")))))
     (((color "faded indigo"))
      ((5 ((color "striped gold")))
       (3 ((color "clear olive")))))
     (((color "faded lavender"))
      ((2 ((color "posh gray")))
       (3 ((color "dark cyan")))
       (4 ((color "muted tan")))))
     (((color "faded lime")) ((2 ((color "wavy yellow")))))
     (((color "faded magenta"))
      ((3 ((color "dim gold")))
       (5 ((color "wavy lavender")))
       (3 ((color "posh brown")))))
     (((color "faded maroon"))
      ((2 ((color "wavy crimson")))
       (3 ((color "faded white")))))
     (((color "faded olive")) ((4 ((color "mirrored chartreuse")))))
     (((color "faded orange")) ((4 ((color "bright bronze")))))
     (((color "faded plum")) ((1 ((color "dull fuchsia")))))
     (((color "faded purple")) ((5 ((color "dark crimson")))))
     (((color "faded red"))
      ((5 ((color "bright plum")))
       (1 ((color "dull violet")))
       (4 ((color "pale yellow")))
       (3 ((color "pale coral")))))
     (((color "faded salmon")) ((1 ((color "wavy yellow")))))
     (((color "faded silver"))
      ((1 ((color "light purple")))
       (3 ((color "bright tomato")))
       (1 ((color "mirrored magenta")))))
     (((color "faded tan")) ((5 ((color "vibrant green")))))
     (((color "faded teal"))
      ((4 ((color "dark blue")))
       (1 ((color "pale brown")))))
     (((color "faded tomato"))
      ((4 ((color "drab coral")))
       (5 ((color "bright lime")))
       (2 ((color "light black")))
       (2 ((color "muted olive")))))
     (((color "faded turquoise"))
      ((3 ((color "bright white")))
       (4 ((color "pale bronze")))
       (5 ((color "pale lavender")))))
     (((color "faded violet")) ((1 ((color "light red")))))
     (((color "faded white"))
      ((2 ((color "pale brown")))
       (3 ((color "muted orange")))
       (3 ((color "dull indigo")))))
     (((color "faded yellow")) ((4 ((color "dotted red")))))
     (((color "light aqua"))
      ((4 ((color "striped gold")))
       (1 ((color "dark blue")))
       (3 ((color "dim red")))
       (2 ((color "wavy gold")))))
     (((color "light beige"))
      ((3 ((color "clear cyan")))
       (5 ((color "dull gold")))
       (4 ((color "dark olive")))))
     (((color "light black"))
      ((2 ((color "wavy crimson")))
       (1 ((color "dull salmon")))
       (4 ((color "muted black")))))
     (((color "light blue"))
      ((4 ((color "posh black")))
       (2 ((color "clear magenta")))))
     (((color "light bronze"))
      ((3 ((color "dark aqua")))
       (4 ((color "striped gold")))))
     (((color "light brown"))
      ((5 ((color "dim white")))
       (3 ((color "muted green")))
       (1 ((color "dull white")))))
     (((color "light chartreuse"))
      ((3 ((color "muted red")))
       (3 ((color "bright violet")))))
     (((color "light coral"))
      ((3 ((color "pale black")))
       (1 ((color "vibrant indigo")))
       (1 ((color "wavy olive")))))
     (((color "light crimson"))
      ((3 ((color "wavy orange")))
       (3 ((color "pale white")))
       (4 ((color "vibrant turquoise")))))
     (((color "light cyan"))
      ((2 ((color "muted silver")))
       (3 ((color "faded salmon")))
       (5 ((color "shiny brown")))
       (5 ((color "drab magenta")))))
     (((color "light fuchsia")) ((2 ((color "dim indigo")))))
     (((color "light gold"))
      ((2 ((color "wavy beige")))
       (5 ((color "plaid salmon")))
       (3 ((color "shiny cyan")))))
     (((color "light gray"))
      ((4 ((color "bright orange")))
       (5 ((color "dull gray")))))
     (((color "light green"))
      ((5 ((color "bright magenta")))
       (1 ((color "light chartreuse")))))
     (((color "light indigo"))
      ((2 ((color "vibrant cyan")))
       (2 ((color "vibrant gray")))))
     (((color "light lavender"))
      ((3 ((color "vibrant turquoise")))
       (1 ((color "pale orange")))
       (4 ((color "shiny orange")))
       (3 ((color "drab turquoise")))))
     (((color "light lime"))
      ((4 ((color "mirrored teal")))
       (4 ((color "dotted cyan")))))
     (((color "light magenta")) ((3 ((color "posh bronze")))))
     (((color "light maroon"))
      ((4 ((color "muted brown")))
       (4 ((color "striped orange")))
       (1 ((color "clear plum")))
       (3 ((color "dull lavender")))))
     (((color "light olive")) ((2 ((color "pale gold")))))
     (((color "light orange"))
      ((1 ((color "dull aqua")))
       (2 ((color "clear silver")))
       (3 ((color "bright tomato")))
       (2 ((color "bright teal")))))
     (((color "light plum"))
      ((4 ((color "muted gold")))
       (1 ((color "muted crimson")))))
     (((color "light purple"))
      ((2 ((color "vibrant purple")))
       (2 ((color "vibrant aqua")))))
     (((color "light red"))
      ((5 ((color "dull magenta")))
       (2 ((color "wavy olive")))
       (3 ((color "drab silver")))
       (1 ((color "dim magenta")))))
     (((color "light salmon")) ((4 ((color "dotted chartreuse")))))
     (((color "light silver"))
      ((3 ((color "mirrored salmon")))
       (4 ((color "pale yellow")))
       (4 ((color "clear silver")))
       (2 ((color "dim olive")))))
     (((color "light tan")) ((4 ((color "wavy blue")))))
     (((color "light teal"))
      ((2 ((color "dotted green")))
       (4 ((color "pale purple")))))
     (((color "light tomato"))
      ((4 ((color "muted red")))
       (3 ((color "muted maroon")))
       (1 ((color "dim teal")))))
     (((color "light turquoise"))
      ((3 ((color "wavy orange")))
       (5 ((color "drab red")))
       (5 ((color "plaid yellow")))))
     (((color "light violet"))
      ((4 ((color "drab blue")))
       (2 ((color "plaid beige")))
       (3 ((color "pale crimson")))))
     (((color "light white"))
      ((5 ((color "faded gray")))
       (1 ((color "dim beige")))
       (5 ((color "bright violet")))))
     (((color "light yellow"))
      ((2 ((color "mirrored orange")))
       (4 ((color "vibrant fuchsia")))
       (5 ((color "drab purple")))))
     (((color "mirrored aqua"))
      ((4 ((color "faded silver")))
       (4 ((color "dull maroon")))
       (3 ((color "dull olive")))
       (4 ((color "dim bronze")))))
     (((color "mirrored beige"))
      ((1 ((color "drab magenta")))
       (4 ((color "clear tan")))
       (5 ((color "mirrored turquoise")))
       (4 ((color "drab tan")))))
     (((color "mirrored black"))
      ((5 ((color "vibrant turquoise")))
       (1 ((color "drab salmon")))
       (5 ((color "pale tan")))))
     (((color "mirrored blue")) ((2 ((color "striped silver")))))
     (((color "mirrored bronze"))
      ((3 ((color "vibrant black")))
       (3 ((color "faded maroon")))
       (1 ((color "drab coral")))
       (1 ((color "muted black")))))
     (((color "mirrored brown")) ((2 ((color "pale black")))))
     (((color "mirrored chartreuse")) ((2 ((color "muted maroon")))))
     (((color "mirrored coral"))
      ((3 ((color "dull maroon")))
       (1 ((color "striped orange")))))
     (((color "mirrored crimson"))
      ((2 ((color "faded tomato")))
       (1 ((color "striped blue")))
       (3 ((color "vibrant green")))
       (3 ((color "striped turquoise")))))
     (((color "mirrored cyan"))
      ((3 ((color "dim chartreuse")))
       (4 ((color "pale aqua")))))
     (((color "mirrored fuchsia"))
      ((4 ((color "faded silver")))
       (4 ((color "plaid gray")))
       (4 ((color "dotted purple")))))
     (((color "mirrored gold"))
      ((4 ((color "muted salmon")))
       (3 ((color "striped black")))
       (3 ((color "dotted red")))
       (3 ((color "dim orange")))))
     (((color "mirrored gray")) ((3 ((color "light tan")))))
     (((color "mirrored green"))
      ((3 ((color "posh salmon")))
       (5 ((color "mirrored purple")))
       (4 ((color "vibrant magenta")))))
     (((color "mirrored indigo"))
      ((1 ((color "dim teal")))
       (3 ((color "drab lavender")))
       (1 ((color "plaid coral")))
       (5 ((color "posh orange")))))
     (((color "mirrored lavender"))
      ((1 ((color "wavy cyan")))
       (2 ((color "drab cyan")))
       (1 ((color "striped olive")))))
     (((color "mirrored lime")) ((2 ((color "posh white")))))
     (((color "mirrored magenta"))
      ((1 ((color "vibrant tan")))
       (1 ((color "wavy turquoise")))
       (4 ((color "clear aqua")))))
     (((color "mirrored maroon"))
      ((3 ((color "dark coral")))
       (4 ((color "clear plum")))))
     (((color "mirrored olive")) ((4 ((color "shiny violet")))))
     (((color "mirrored orange"))
      ((3 ((color "light purple")))
       (4 ((color "dull lavender")))
       (1 ((color "bright bronze")))
       (4 ((color "pale black")))))
     (((color "mirrored plum"))
      ((3 ((color "vibrant aqua")))
       (3 ((color "vibrant turquoise")))
       (5 ((color "faded orange")))
       (1 ((color "bright violet")))))
     (((color "mirrored purple"))
      ((5 ((color "posh plum")))
       (1 ((color "light purple")))
       (2 ((color "plaid aqua")))
       (5 ((color "striped gold")))))
     (((color "mirrored red"))
      ((5 ((color "plaid aqua")))
       (4 ((color "clear cyan")))
       (1 ((color "mirrored magenta")))))
     (((color "mirrored salmon"))
      ((4 ((color "striped purple")))
       (1 ((color "vibrant black")))
       (4 ((color "drab green")))))
     (((color "mirrored silver"))
      ((1 ((color "dull brown")))
       (4 ((color "pale black")))
       (2 ((color "mirrored plum")))
       (1 ((color "dotted red")))))
     (((color "mirrored tan"))
      ((1 ((color "dotted fuchsia")))
       (2 ((color "vibrant lavender")))))
     (((color "mirrored teal")) ((3 ((color "faded orange")))))
     (((color "mirrored tomato")) ((4 ((color "dotted plum")))))
     (((color "mirrored turquoise"))
      ((3 ((color "dull gray")))
       (4 ((color "muted turquoise")))
       (4 ((color "dull indigo")))))
     (((color "mirrored violet"))
      ((2 ((color "mirrored magenta")))
       (1 ((color "dotted cyan")))
       (2 ((color "dark beige")))
       (1 ((color "mirrored plum")))))
     (((color "mirrored white"))
      ((3 ((color "muted turquoise")))
       (5 ((color "striped gray")))
       (1 ((color "faded lime")))))
     (((color "mirrored yellow"))
      ((1 ((color "drab turquoise")))
       (5 ((color "drab teal")))
       (3 ((color "light cyan")))
       (5 ((color "wavy gray")))))
     (((color "muted aqua"))
      ((3 ((color "muted black")))
       (2 ((color "posh cyan")))))
     (((color "muted beige"))
      ((5 ((color "bright bronze")))
       (3 ((color "dull olive")))))
     (((color "muted black"))
      ((3 ((color "faded white")))
       (5 ((color "pale crimson")))
       (3 ((color "muted brown")))
       (1 ((color "vibrant tan")))))
     (((color "muted blue"))
      ((4 ((color "shiny violet")))
       (5 ((color "muted tomato")))
       (5 ((color "light salmon")))))
     (((color "muted bronze"))
      ((2 ((color "drab salmon")))
       (1 ((color "mirrored orange")))
       (2 ((color "light coral")))
       (4 ((color "clear plum")))))
     (((color "muted brown")) ((5 ((color "wavy yellow")))))
     (((color "muted chartreuse"))
      ((2 ((color "pale crimson")))
       (2 ((color "mirrored black")))
       (5 ((color "dark purple")))
       (3 ((color "wavy tan")))))
     (((color "muted coral")) ((3 ((color "dark green")))))
     (((color "muted crimson"))
      ((1 ((color "striped cyan")))
       (1 ((color "vibrant bronze")))
       (1 ((color "dull coral")))
       (4 ((color "vibrant black")))))
     (((color "muted cyan"))
      ((1 ((color "mirrored lavender")))
       (1 ((color "shiny blue")))))
     (((color "muted fuchsia"))
      ((3 ((color "dim purple")))
       (2 ((color "pale cyan")))
       (4 ((color "pale gray")))
       (3 ((color "drab salmon")))))
     (((color "muted gold")) ((1 ((color "dim orange")))))
     (((color "muted gray")) ((2 ((color "muted coral")))))
     (((color "muted green"))
      ((2 ((color "drab red")))
       (1 ((color "drab tan")))))
     (((color "muted indigo"))
      ((2 ((color "pale cyan")))
       (5 ((color "striped brown")))
       (3 ((color "striped red")))))
     (((color "muted lavender"))
      ((1 ((color "clear crimson")))
       (5 ((color "light white")))))
     (((color "muted lime"))
      ((5 ((color "plaid olive")))
       (4 ((color "muted orange")))))
     (((color "muted magenta"))
      ((3 ((color "shiny green")))
       (4 ((color "pale aqua")))))
     (((color "muted maroon")) ((1 ((color "plaid indigo")))))
     (((color "muted olive"))
      ((2 ((color "dark brown")))
       (5 ((color "bright white")))))
     (((color "muted orange"))
      ((1 ((color "dotted chartreuse")))
       (2 ((color "pale blue")))
       (3 ((color "muted brown")))
       (1 ((color "posh tomato")))))
     (((color "muted plum")) ((1 ((color "dark beige")))))
     (((color "muted purple")) ((4 ((color "striped purple")))))
     (((color "muted red"))
      ((4 ((color "dark orange")))
       (3 ((color "light black")))))
     (((color "muted salmon"))
      ((2 ((color "light cyan")))
       (4 ((color "dull tomato")))
       (2 ((color "pale chartreuse")))
       (1 ((color "dotted gray")))))
     (((color "muted silver"))
      ((3 ((color "dotted cyan")))
       (3 ((color "muted fuchsia")))
       (5 ((color "plaid purple")))))
     (((color "muted tan"))
      ((2 ((color "muted tomato")))
       (2 ((color "light white")))
       (4 ((color "wavy lavender")))
       (2 ((color "dim turquoise")))))
     (((color "muted teal"))
      ((5 ((color "bright violet")))
       (4 ((color "pale cyan")))))
     (((color "muted tomato"))
      ((2 ((color "pale blue")))
       (2 ((color "shiny bronze")))
       (1 ((color "light teal")))))
     (((color "muted turquoise"))
      ((5 ((color "pale tan")))
       (4 ((color "dim olive")))
       (2 ((color "plaid indigo")))))
     (((color "muted violet"))
      ((3 ((color "bright fuchsia")))
       (1 ((color "muted tomato")))
       (4 ((color "drab lime")))
       (2 ((color "dim olive")))))
     (((color "muted white"))
      ((3 ((color "plaid violet")))
       (1 ((color "dim black")))))
     (((color "muted yellow"))
      ((3 ((color "drab bronze")))
       (2 ((color "pale gray")))))
     (((color "pale aqua")) ((3 ((color "light bronze")))))
     (((color "pale beige"))
      ((2 ((color "muted red")))
       (2 ((color "clear tomato")))
       (3 ((color "posh olive")))))
     (((color "pale black"))
      ((1 ((color "plaid coral")))
       (4 ((color "vibrant turquoise")))
       (1 ((color "pale brown")))))
     (((color "pale blue")) ())
     (((color "pale bronze"))
      ((4 ((color "mirrored coral")))
       (2 ((color "muted red")))))
     (((color "pale brown"))
      ((4 ((color "wavy green")))
       (1 ((color "wavy yellow")))))
     (((color "pale chartreuse"))
      ((4 ((color "bright purple")))
       (1 ((color "posh salmon")))))
     (((color "pale coral"))
      ((5 ((color "dim silver")))
       (3 ((color "clear gray")))))
     (((color "pale crimson"))
      ((1 ((color "pale blue")))
       (4 ((color "clear plum")))
       (5 ((color "wavy yellow")))
       (1 ((color "dotted purple")))))
     (((color "pale cyan"))
      ((5 ((color "dull gray")))
       (3 ((color "posh olive")))
       (2 ((color "striped silver")))))
     (((color "pale fuchsia"))
      ((3 ((color "pale beige")))
       (5 ((color "plaid blue")))
       (3 ((color "light violet")))
       (3 ((color "striped blue")))))
     (((color "pale gold")) ((5 ((color "striped olive")))))
     (((color "pale gray"))
      ((4 ((color "wavy yellow")))
       (2 ((color "vibrant tan")))
       (2 ((color "pale tan")))
       (1 ((color "dark coral")))))
     (((color "pale green"))
      ((2 ((color "dotted chartreuse")))
       (3 ((color "plaid magenta")))))
     (((color "pale indigo"))
      ((1 ((color "dull green")))
       (5 ((color "drab olive")))
       (5 ((color "dull salmon")))
       (5 ((color "dark cyan")))))
     (((color "pale lavender"))
      ((3 ((color "dotted red")))
       (1 ((color "bright green")))
       (1 ((color "bright violet")))))
     (((color "pale lime"))
      ((2 ((color "plaid blue")))
       (1 ((color "bright violet")))
       (5 ((color "faded bronze")))
       (1 ((color "dotted plum")))))
     (((color "pale magenta"))
      ((1 ((color "drab coral")))
       (5 ((color "plaid blue")))
       (1 ((color "wavy yellow")))
       (5 ((color "dark salmon")))))
     (((color "pale maroon")) ((3 ((color "dull fuchsia")))))
     (((color "pale olive"))
      ((4 ((color "mirrored black")))
       (1 ((color "dull magenta")))))
     (((color "pale orange"))
      ((2 ((color "vibrant aqua")))
       (2 ((color "vibrant green")))
       (1 ((color "bright coral")))))
     (((color "pale plum"))
      ((4 ((color "wavy blue")))
       (3 ((color "posh bronze")))
       (4 ((color "pale lime")))))
     (((color "pale purple"))
      ((3 ((color "dull salmon")))
       (1 ((color "drab cyan")))
       (5 ((color "bright green")))
       (5 ((color "drab salmon")))))
     (((color "pale red"))
      ((4 ((color "mirrored cyan")))
       (4 ((color "clear gray")))
       (2 ((color "dotted tan")))))
     (((color "pale salmon"))
      ((4 ((color "plaid coral")))
       (5 ((color "wavy yellow")))
       (2 ((color "light coral")))))
     (((color "pale silver"))
      ((4 ((color "wavy orange")))
       (4 ((color "dotted green")))
       (3 ((color "drab silver")))))
     (((color "pale tan"))
      ((1 ((color "shiny bronze")))
       (4 ((color "dim coral")))
       (4 ((color "vibrant green")))
       (4 ((color "dotted gold")))))
     (((color "pale teal"))
      ((4 ((color "dim lime")))
       (4 ((color "pale crimson")))
       (2 ((color "clear lavender")))))
     (((color "pale tomato"))
      ((3 ((color "dull teal")))
       (4 ((color "vibrant green")))
       (1 ((color "bright crimson")))))
     (((color "pale turquoise")) ((4 ((color "wavy maroon")))))
     (((color "pale violet")) ((1 ((color "faded white")))))
     (((color "pale white"))
      ((2 ((color "dotted gold")))
       (3 ((color "dotted lavender")))))
     (((color "pale yellow"))
      ((4 ((color "muted silver")))
       (4 ((color "dull teal")))
       (4 ((color "muted purple")))))
     (((color "plaid aqua")) ((2 ((color "muted teal")))))
     (((color "plaid beige"))
      ((5 ((color "bright beige")))
       (4 ((color "pale black")))))
     (((color "plaid black"))
      ((3 ((color "light violet")))
       (3 ((color "mirrored bronze")))
       (1 ((color "clear blue")))
       (5 ((color "clear olive")))))
     (((color "plaid blue")) ((5 ((color "bright purple")))))
     (((color "plaid bronze")) ((4 ((color "dull green")))))
     (((color "plaid brown"))
      ((4 ((color "dull teal")))
       (2 ((color "wavy beige")))))
     (((color "plaid chartreuse"))
      ((1 ((color "light silver")))
       (5 ((color "vibrant green")))
       (3 ((color "wavy lavender")))
       (4 ((color "vibrant turquoise")))))
     (((color "plaid coral"))
      ((4 ((color "vibrant indigo")))
       (3 ((color "bright bronze")))
       (1 ((color "dotted purple")))))
     (((color "plaid crimson"))
      ((5 ((color "wavy crimson")))
       (5 ((color "clear crimson")))
       (4 ((color "vibrant red")))))
     (((color "plaid cyan")) ())
     (((color "plaid fuchsia")) ((3 ((color "dull lavender")))))
     (((color "plaid gold")) ((5 ((color "dim chartreuse")))))
     (((color "plaid gray"))
      ((1 ((color "muted brown")))
       (3 ((color "shiny brown")))))
     (((color "plaid green"))
      ((2 ((color "wavy red")))
       (1 ((color "pale yellow")))
       (5 ((color "posh black")))))
     (((color "plaid indigo"))
      ((4 ((color "drab silver")))
       (2 ((color "dotted purple")))
       (3 ((color "vibrant green")))
       (2 ((color "vibrant aqua")))))
     (((color "plaid lavender")) ((2 ((color "light purple")))))
     (((color "plaid lime"))
      ((4 ((color "dotted chartreuse")))
       (2 ((color "plaid orange")))
       (4 ((color "shiny fuchsia")))))
     (((color "plaid magenta")) ((5 ((color "striped magenta")))))
     (((color "plaid maroon"))
      ((3 ((color "wavy olive")))
       (5 ((color "pale plum")))
       (2 ((color "dark beige")))
       (4 ((color "striped white")))))
     (((color "plaid olive"))
      ((5 ((color "posh tomato")))
       (3 ((color "faded bronze")))
       (4 ((color "pale white")))))
     (((color "plaid orange"))
      ((2 ((color "vibrant bronze")))
       (3 ((color "pale silver")))
       (1 ((color "shiny blue")))
       (3 ((color "plaid maroon")))))
     (((color "plaid plum"))
      ((1 ((color "drab cyan")))
       (5 ((color "light lime")))
       (4 ((color "muted lavender")))))
     (((color "plaid purple"))
      ((4 ((color "light coral")))
       (4 ((color "faded salmon")))))
     (((color "plaid red")) ((4 ((color "faded coral")))))
     (((color "plaid salmon"))
      ((1 ((color "striped tan")))
       (3 ((color "pale blue")))))
     (((color "plaid silver"))
      ((4 ((color "dim plum")))
       (1 ((color "dim beige")))
       (3 ((color "plaid salmon")))))
     (((color "plaid tan")) ((1 ((color "pale cyan")))))
     (((color "plaid teal"))
      ((4 ((color "mirrored magenta")))
       (3 ((color "dotted red")))))
     (((color "plaid tomato"))
      ((1 ((color "light bronze")))
       (2 ((color "posh plum")))))
     (((color "plaid turquoise"))
      ((2 ((color "pale tomato")))
       (4 ((color "faded white")))
       (4 ((color "bright teal")))))
     (((color "plaid violet")) ((5 ((color "mirrored plum")))))
     (((color "plaid white")) ((1 ((color "pale brown")))))
     (((color "plaid yellow")) ((3 ((color "bright silver")))))
     (((color "posh aqua")) ((3 ((color "bright olive")))))
     (((color "posh beige"))
      ((2 ((color "dotted turquoise")))
       (3 ((color "vibrant tan")))
       (4 ((color "pale orange")))
       (4 ((color "bright salmon")))))
     (((color "posh black"))
      ((5 ((color "dotted tan")))
       (3 ((color "muted orange")))
       (2 ((color "dim purple")))
       (1 ((color "shiny cyan")))))
     (((color "posh blue"))
      ((2 ((color "vibrant brown")))
       (3 ((color "vibrant salmon")))))
     (((color "posh bronze"))
      ((3 ((color "dull orange")))
       (4 ((color "dull salmon")))
       (5 ((color "clear blue")))))
     (((color "posh brown")) ((1 ((color "drab yellow")))))
     (((color "posh chartreuse"))
      ((4 ((color "dark purple")))
       (3 ((color "muted magenta")))
       (2 ((color "faded black")))))
     (((color "posh coral"))
      ((5 ((color "drab yellow")))
       (2 ((color "faded white")))))
     (((color "posh crimson")) ((2 ((color "light white")))))
     (((color "posh cyan"))
      ((3 ((color "faded coral")))
       (5 ((color "light maroon")))
       (3 ((color "faded indigo")))))
     (((color "posh fuchsia")) ((5 ((color "dark lavender")))))
     (((color "posh gold")) ((5 ((color "dotted red")))))
     (((color "posh gray")) ((2 ((color "clear plum")))))
     (((color "posh green")) ((1 ((color "plaid silver")))))
     (((color "posh indigo"))
      ((1 ((color "mirrored maroon")))
       (4 ((color "striped indigo")))))
     (((color "posh lavender"))
      ((2 ((color "faded tomato")))
       (4 ((color "dim crimson")))))
     (((color "posh lime"))
      ((3 ((color "faded brown")))
       (4 ((color "wavy brown")))))
     (((color "posh magenta"))
      ((3 ((color "posh salmon")))
       (5 ((color "bright bronze")))
       (5 ((color "mirrored maroon")))
       (2 ((color "vibrant purple")))))
     (((color "posh maroon"))
      ((2 ((color "dark teal")))
       (3 ((color "dim violet")))
       (5 ((color "mirrored tan")))))
     (((color "posh olive"))
      ((1 ((color "vibrant chartreuse")))
       (4 ((color "posh salmon")))
       (5 ((color "plaid coral")))))
     (((color "posh orange"))
      ((5 ((color "pale crimson")))
       (1 ((color "bright blue")))
       (5 ((color "clear green")))))
     (((color "posh plum"))
      ((3 ((color "dim beige")))
       (1 ((color "wavy magenta")))
       (3 ((color "dull fuchsia")))
       (4 ((color "dull gold")))))
     (((color "posh purple"))
      ((2 ((color "wavy black")))
       (4 ((color "vibrant salmon")))))
     (((color "posh red"))
      ((4 ((color "vibrant bronze")))
       (4 ((color "wavy beige")))))
     (((color "posh salmon")) ())
     (((color "posh silver"))
      ((4 ((color "muted black")))
       (5 ((color "pale cyan")))
       (2 ((color "dark plum")))
       (1 ((color "shiny bronze")))))
     (((color "posh tan"))
      ((2 ((color "plaid tan")))
       (5 ((color "drab red")))
       (5 ((color "vibrant salmon")))
       (1 ((color "plaid salmon")))))
     (((color "posh teal"))
      ((5 ((color "muted green")))
       (1 ((color "dotted brown")))))
     (((color "posh tomato")) ((1 ((color "muted brown")))))
     (((color "posh turquoise"))
      ((5 ((color "plaid fuchsia")))
       (5 ((color "pale blue")))
       (3 ((color "vibrant green")))))
     (((color "posh violet")) ((3 ((color "clear red")))))
     (((color "posh white"))
      ((4 ((color "light lime")))
       (1 ((color "muted teal")))
       (1 ((color "dull aqua")))))
     (((color "posh yellow"))
      ((1 ((color "posh silver")))
       (3 ((color "dotted gold")))))
     (((color "shiny aqua"))
      ((1 ((color "bright blue")))
       (4 ((color "drab green")))
       (2 ((color "light teal")))
       (2 ((color "dotted green")))))
     (((color "shiny beige")) ((2 ((color "wavy red")))))
     (((color "shiny black"))
      ((2 ((color "plaid blue")))
       (5 ((color "drab salmon")))))
     (((color "shiny blue"))
      ((3 ((color "dark coral")))
       (4 ((color "bright purple")))
       (2 ((color "pale cyan")))
       (5 ((color "plaid indigo")))))
     (((color "shiny bronze")) ((1 ((color "pale blue")))))
     (((color "shiny brown")) ())
     (((color "shiny chartreuse"))
      ((3 ((color "mirrored green")))
       (3 ((color "dark salmon")))))
     (((color "shiny coral"))
      ((4 ((color "wavy magenta")))
       (5 ((color "dark olive")))))
     (((color "shiny crimson"))
      ((4 ((color "drab green")))
       (3 ((color "posh lime")))
       (2 ((color "striped magenta")))
       (2 ((color "bright teal")))))
     (((color "shiny cyan")) ((4 ((color "bright violet")))))
     (((color "shiny fuchsia"))
      ((5 ((color "clear green")))
       (5 ((color "muted tomato")))
       (1 ((color "dark coral")))
       (5 ((color "wavy blue")))))
     (((color "shiny gold"))
      ((5 ((color "muted orange")))
       (2 ((color "faded tan")))
       (3 ((color "faded orange")))
       (1 ((color "dull brown")))))
     (((color "shiny gray"))
      ((3 ((color "wavy indigo")))
       (5 ((color "striped gold")))
       (1 ((color "drab cyan")))))
     (((color "shiny green"))
      ((3 ((color "shiny brown")))
       (5 ((color "dim coral")))))
     (((color "shiny indigo"))
      ((1 ((color "dull lavender")))
       (3 ((color "vibrant tan")))
       (4 ((color "faded lime")))
       (5 ((color "drab tan")))))
     (((color "shiny lavender")) ((5 ((color "mirrored plum")))))
     (((color "shiny lime")) ((1 ((color "light tan")))))
     (((color "shiny magenta")) ((2 ((color "dotted fuchsia")))))
     (((color "shiny maroon"))
      ((3 ((color "dotted crimson")))
       (5 ((color "bright teal")))
       (5 ((color "dotted fuchsia")))
       (4 ((color "dull green")))))
     (((color "shiny olive"))
      ((3 ((color "plaid teal")))
       (3 ((color "vibrant fuchsia")))))
     (((color "shiny orange"))
      ((2 ((color "bright green")))
       (4 ((color "shiny lime")))
       (1 ((color "striped red")))
       (5 ((color "dull turquoise")))))
     (((color "shiny plum"))
      ((1 ((color "faded lime")))
       (4 ((color "faded orange")))
       (2 ((color "vibrant beige")))
       (2 ((color "striped orange")))))
     (((color "shiny purple"))
      ((3 ((color "shiny salmon")))
       (5 ((color "posh plum")))
       (1 ((color "striped white")))
       (5 ((color "shiny black")))))
     (((color "shiny red"))
      ((4 ((color "light purple")))
       (2 ((color "dull orange")))
       (4 ((color "striped magenta")))
       (3 ((color "dull red")))))
     (((color "shiny salmon")) ((3 ((color "dim magenta")))))
     (((color "shiny silver"))
      ((1 ((color "dotted gold")))
       (4 ((color "plaid tomato")))))
     (((color "shiny tan"))
      ((4 ((color "dim beige")))
       (2 ((color "pale tomato")))))
     (((color "shiny teal"))
      ((5 ((color "dim purple")))
       (3 ((color "faded violet")))
       (5 ((color "plaid crimson")))))
     (((color "shiny tomato"))
      ((5 ((color "vibrant aqua")))
       (3 ((color "clear tan")))))
     (((color "shiny turquoise"))
      ((3 ((color "plaid blue")))
       (3 ((color "dim salmon")))
       (5 ((color "dull gold")))))
     (((color "shiny violet"))
      ((1 ((color "dull red")))
       (4 ((color "wavy indigo")))
       (1 ((color "clear violet")))
       (2 ((color "dotted white")))))
     (((color "shiny white"))
      ((2 ((color "dark beige")))
       (4 ((color "clear aqua")))))
     (((color "shiny yellow")) ((5 ((color "muted orange")))))
     (((color "striped aqua"))
      ((1 ((color "pale aqua")))
       (2 ((color "muted yellow")))
       (4 ((color "pale maroon")))
       (2 ((color "shiny coral")))))
     (((color "striped beige"))
      ((1 ((color "pale olive")))
       (3 ((color "shiny purple")))
       (1 ((color "dull salmon")))))
     (((color "striped black"))
      ((1 ((color "faded chartreuse")))
       (2 ((color "dull brown")))
       (4 ((color "clear cyan")))
       (1 ((color "light teal")))))
     (((color "striped blue")) ((3 ((color "pale white")))))
     (((color "striped bronze"))
      ((2 ((color "pale lavender")))
       (1 ((color "dull brown")))))
     (((color "striped brown")) ((5 ((color "dark black")))))
     (((color "striped chartreuse"))
      ((2 ((color "striped yellow")))
       (1 ((color "shiny orange")))
       (1 ((color "dotted turquoise")))
       (2 ((color "pale violet")))))
     (((color "striped coral")) ((4 ((color "pale gray")))))
     (((color "striped crimson")) ((4 ((color "muted teal")))))
     (((color "striped cyan")) ((5 ((color "clear beige")))))
     (((color "striped fuchsia")) ((4 ((color "muted magenta")))))
     (((color "striped gold")) ((3 ((color "dotted gray")))))
     (((color "striped gray")) ((5 ((color "pale chartreuse")))))
     (((color "striped green"))
      ((1 ((color "mirrored red")))
       (3 ((color "shiny blue")))))
     (((color "striped indigo"))
      ((4 ((color "clear violet")))
       (5 ((color "dotted yellow")))
       (4 ((color "clear tomato")))))
     (((color "striped lavender"))
      ((2 ((color "plaid lime")))
       (4 ((color "dark white")))))
     (((color "striped lime"))
      ((2 ((color "bright chartreuse")))
       (2 ((color "striped orange")))))
     (((color "striped magenta"))
      ((2 ((color "shiny white")))
       (1 ((color "shiny brown")))
       (2 ((color "bright tomato")))))
     (((color "striped maroon")) ((5 ((color "shiny magenta")))))
     (((color "striped olive"))
      ((5 ((color "posh tomato")))
       (1 ((color "pale purple")))))
     (((color "striped orange")) ((3 ((color "clear aqua")))))
     (((color "striped plum"))
      ((4 ((color "dark tan")))
       (2 ((color "mirrored teal")))
       (1 ((color "striped brown")))))
     (((color "striped purple")) ())
     (((color "striped red")) ((1 ((color "plaid indigo")))))
     (((color "striped salmon"))
      ((5 ((color "dark gray")))
       (1 ((color "muted tomato")))))
     (((color "striped silver"))
      ((2 ((color "shiny bronze")))
       (5 ((color "striped purple")))))
     (((color "striped tan"))
      ((2 ((color "light purple")))
       (3 ((color "mirrored blue")))
       (5 ((color "dim magenta")))))
     (((color "striped teal")) ((2 ((color "bright tan")))))
     (((color "striped tomato"))
      ((3 ((color "plaid tan")))
       (3 ((color "pale bronze")))
       (4 ((color "dull yellow")))
       (3 ((color "drab magenta")))))
     (((color "striped turquoise"))
      ((5 ((color "bright green")))
       (5 ((color "dark bronze")))
       (3 ((color "pale crimson")))))
     (((color "striped violet")) ((1 ((color "muted tomato")))))
     (((color "striped white"))
      ((4 ((color "pale maroon")))
       (4 ((color "dull yellow")))
       (3 ((color "mirrored white")))))
     (((color "striped yellow"))
      ((3 ((color "dim teal")))
       (5 ((color "clear maroon")))
       (1 ((color "light cyan")))))
     (((color "vibrant aqua")) ((4 ((color "posh salmon")))))
     (((color "vibrant beige"))
      ((3 ((color "drab silver")))
       (4 ((color "wavy orange")))
       (3 ((color "pale brown")))
       (2 ((color "faded orange")))))
     (((color "vibrant black")) ((1 ((color "drab magenta")))))
     (((color "vibrant blue"))
      ((2 ((color "dim turquoise")))
       (4 ((color "plaid lime")))
       (2 ((color "faded turquoise")))
       (4 ((color "faded gold")))))
     (((color "vibrant bronze"))
      ((5 ((color "dim silver")))
       (4 ((color "dotted fuchsia")))
       (1 ((color "vibrant gray")))
       (1 ((color "muted brown")))))
     (((color "vibrant brown")) ((4 ((color "dim red")))))
     (((color "vibrant chartreuse"))
      ((5 ((color "dull gray")))
       (2 ((color "bright purple")))))
     (((color "vibrant coral"))
      ((1 ((color "dotted violet")))
       (3 ((color "faded gray")))
       (3 ((color "pale magenta")))))
     (((color "vibrant crimson"))
      ((2 ((color "pale black")))
       (5 ((color "mirrored silver")))
       (1 ((color "clear beige")))
       (5 ((color "drab yellow")))))
     (((color "vibrant cyan"))
      ((1 ((color "striped purple")))
       (4 ((color "muted black")))))
     (((color "vibrant fuchsia")) ((3 ((color "mirrored coral")))))
     (((color "vibrant gold")) ((5 ((color "vibrant tan")))))
     (((color "vibrant gray")) ((5 ((color "wavy yellow")))))
     (((color "vibrant green"))
      ((4 ((color "posh salmon")))
       (4 ((color "plaid cyan")))
       (3 ((color "clear plum")))))
     (((color "vibrant indigo"))
      ((2 ((color "striped purple")))
       (4 ((color "vibrant green")))
       (3 ((color "dotted purple")))
       (1 ((color "vibrant turquoise")))))
     (((color "vibrant lavender")) ((3 ((color "dim bronze")))))
     (((color "vibrant lime"))
      ((4 ((color "shiny maroon")))
       (2 ((color "shiny plum")))
       (3 ((color "dull green")))))
     (((color "vibrant magenta"))
      ((5 ((color "posh plum")))
       (2 ((color "mirrored turquoise")))
       (2 ((color "light red")))
       (2 ((color "pale plum")))))
     (((color "vibrant maroon"))
      ((5 ((color "shiny brown")))
       (2 ((color "faded black")))
       (1 ((color "drab silver")))))
     (((color "vibrant olive"))
      ((3 ((color "muted turquoise")))
       (5 ((color "wavy blue")))
       (1 ((color "dotted silver")))
       (5 ((color "striped tan")))))
     (((color "vibrant orange"))
      ((4 ((color "dotted yellow")))
       (4 ((color "plaid cyan")))))
     (((color "vibrant plum"))
      ((5 ((color "dotted yellow")))
       (2 ((color "plaid white")))
       (5 ((color "drab red")))
       (4 ((color "clear lavender")))))
     (((color "vibrant purple")) ((5 ((color "vibrant aqua")))))
     (((color "vibrant red"))
      ((3 ((color "vibrant salmon")))
       (2 ((color "plaid teal")))
       (2 ((color "dull gray")))
       (2 ((color "vibrant gray")))))
     (((color "vibrant salmon")) ((4 ((color "dim purple")))))
     (((color "vibrant silver"))
      ((2 ((color "faded gray")))
       (3 ((color "mirrored orange")))
       (4 ((color "clear black")))
       (2 ((color "pale lavender")))))
     (((color "vibrant tan"))
      ((2 ((color "dull brown")))
       (1 ((color "vibrant indigo")))
       (1 ((color "dim crimson")))))
     (((color "vibrant teal")) ((5 ((color "dotted gold")))))
     (((color "vibrant tomato"))
      ((5 ((color "faded tomato")))
       (3 ((color "muted silver")))
       (5 ((color "dotted turquoise")))))
     (((color "vibrant turquoise")) ())
     (((color "vibrant violet"))
      ((4 ((color "striped purple")))
       (4 ((color "light cyan")))
       (5 ((color "faded tan")))
       (4 ((color "light yellow")))))
     (((color "vibrant white"))
      ((1 ((color "dim olive")))
       (2 ((color "bright silver")))
       (2 ((color "muted blue")))))
     (((color "vibrant yellow"))
      ((2 ((color "mirrored lavender")))
       (1 ((color "light orange")))))
     (((color "wavy aqua"))
      ((4 ((color "drab gray")))
       (3 ((color "muted yellow")))
       (5 ((color "shiny lavender")))
       (2 ((color "plaid turquoise")))))
     (((color "wavy beige"))
      ((1 ((color "dark plum")))
       (2 ((color "dull lavender")))
       (2 ((color "drab green")))))
     (((color "wavy black"))
      ((1 ((color "faded indigo")))
       (4 ((color "dim salmon")))
       (1 ((color "drab aqua")))
       (5 ((color "dull maroon")))))
     (((color "wavy blue")) ())
     (((color "wavy bronze"))
      ((2 ((color "pale purple")))
       (1 ((color "pale teal")))
       (1 ((color "muted bronze")))
       (1 ((color "mirrored beige")))))
     (((color "wavy brown"))
      ((4 ((color "vibrant indigo")))
       (2 ((color "vibrant green")))
       (5 ((color "wavy blue")))
       (3 ((color "dim magenta")))))
     (((color "wavy chartreuse"))
      ((3 ((color "dim coral")))
       (4 ((color "bright chartreuse")))
       (5 ((color "pale plum")))))
     (((color "wavy coral"))
      ((4 ((color "pale purple")))
       (2 ((color "bright olive")))))
     (((color "wavy crimson"))
      ((2 ((color "dim olive")))
       (4 ((color "mirrored black")))
       (4 ((color "faded salmon")))))
     (((color "wavy cyan"))
      ((1 ((color "dim magenta")))
       (2 ((color "shiny blue")))))
     (((color "wavy fuchsia"))
      ((5 ((color "light gray")))
       (3 ((color "wavy beige")))))
     (((color "wavy gold"))
      ((2 ((color "dull gray")))
       (1 ((color "dark lavender")))
       (3 ((color "pale gray")))))
     (((color "wavy gray"))
      ((5 ((color "dim green")))
       (1 ((color "plaid blue")))))
     (((color "wavy green"))
      ((1 ((color "dull brown")))
       (1 ((color "clear plum")))))
     (((color "wavy indigo")) ((4 ((color "bright crimson")))))
     (((color "wavy lavender")) ((3 ((color "shiny lime")))))
     (((color "wavy lime")) ((1 ((color "clear blue")))))
     (((color "wavy magenta")) ((1 ((color "muted fuchsia")))))
     (((color "wavy maroon")) ((4 ((color "dark gold")))))
     (((color "wavy olive"))
      ((1 ((color "shiny bronze")))
       (5 ((color "plaid coral")))
       (3 ((color "dotted gold")))
       (1 ((color "pale brown")))))
     (((color "wavy orange"))
      ((2 ((color "mirrored maroon")))
       (1 ((color "striped silver")))
       (2 ((color "wavy yellow")))
       (2 ((color "dim crimson")))))
     (((color "wavy plum"))
      ((1 ((color "clear gray")))
       (4 ((color "dark teal")))
       (5 ((color "faded gray")))))
     (((color "wavy purple"))
      ((3 ((color "pale bronze")))
       (5 ((color "shiny maroon")))
       (4 ((color "dotted teal")))
       (4 ((color "pale indigo")))))
     (((color "wavy red"))
      ((2 ((color "drab silver")))
       (3 ((color "shiny salmon")))))
     (((color "wavy salmon"))
      ((4 ((color "clear tomato")))
       (4 ((color "bright bronze")))
       (5 ((color "posh purple")))
       (5 ((color "faded black")))))
     (((color "wavy silver")) ((1 ((color "plaid indigo")))))
     (((color "wavy tan")) ((2 ((color "vibrant tan")))))
     (((color "wavy teal"))
      ((4 ((color "vibrant indigo")))
       (2 ((color "vibrant turquoise")))))
     (((color "wavy tomato"))
      ((3 ((color "bright fuchsia")))
       (2 ((color "dull fuchsia")))
       (4 ((color "pale brown")))))
     (((color "wavy turquoise"))
      ((2 ((color "drab silver")))
       (2 ((color "vibrant purple")))
       (3 ((color "faded tan")))))
     (((color "wavy violet"))
      ((4 ((color "posh chartreuse")))
       (2 ((color "mirrored tomato")))))
     (((color "wavy white"))
      ((3 ((color "striped maroon")))
       (5 ((color "striped aqua")))
       (4 ((color "dull fuchsia")))
       (1 ((color "wavy orange")))))
     (((color "wavy yellow")) ())) |}]
  in
  return ()
;;
